parameters:
#    health_system.example.class: HealthSystem\HealthSystemBundle\Example

services:
#    health_system.example:
#        class: %health_system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
